#!/bin/sh

set -x

LOG_FILE=/var/log/netbird/client_pre_install.log
AGENT=/usr/local/bin/netibird-awg

mkdir -p /var/log/netbird/

{
    # check if it was installed with brew
    if brew list --formula | grep -q '^netibird-awg$'
    then
        echo "Netibird-AWG is managed by Brew. Use Brew to update it."
        exit 1
    fi
    osascript -e 'quit app "Netibird-AWG"' || true
    if [ -x "$AGENT" ]; then
        "$AGENT" service stop || true
    fi
    echo "Preinstall complete"
    exit 0 # all good
} > "$LOG_FILE" 2>&1
